import time

print('\r|         |', end='')
time.sleep(1)
print('\r|>        |', end='')
time.sleep(1)
print('\r|=>       |', end='')
time.sleep(1)
print('\r|==>      |', end='')
time.sleep(1)
print('\r|===>     |', end='')
time.sleep(1)
print('\r|====>    |', end='')
time.sleep(1)
print('\r|=====>   |', end='')
time.sleep(1)
print('\r|======>  |', end='')
time.sleep(1)
print('\r|=======> |', end='')
time.sleep(1)
print('\r|========>|', end='')
time.sleep(1)
print('\r|=========|', end='')
print('Done')